### ISSUE TITLE
Creating new user

### ISSUE THREAD

**Issue by edwinharly** [BurkovBA/django-rest-framework-mongoengine-example#7]
Hi there, if I want to create a new user through POST request on users endpoint, do I need to define a post function on UserViewSet class ? Or maybe there's already an existing way to create user through some endpoint ? Thanks.

**Comment by franciscbalint** [comment]
You need to overwrite the default user class (not recommended) https://stackoverflow.com/questions/21072595/mongoengine-how-to-custom-user-model-custom-backend-for-authenticate

**Comment by edwinharly** [comment]
So, what is the recommended way to handle user registration ?

**Comment by franciscbalint** [comment]
"In retrospect, I guess the moral is: never use Mongo just because it's cool. Mongo is still a second-class citizen in the Django world." 

I used MongoDB for custom models and let default models on postgres.

**Comment by BurkovBA** [comment]
@edwinharly Yes, I think, you need to add a custom `create()` method for UserViewSet.

As for how users system works in Django with Mongoengine: Mongoengine 0.9- contains a [django submodule](https://github.com/MongoEngine/mongoengine/tree/0.9/mongoengine/django), which implements a [dummy Django model](https://github.com/MongoEngine/mongoengine/blob/0.9/mongoengine/django/mongo_auth/models.py#L97) that proxies all the meaningful action to a [Mongoengine user document](https://github.com/MongoEngine/mongoengine/blob/0.9/mongoengine/django/auth.py#L202).
